# Generated by Django 3.1.1 on 2021-01-28 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], max_length=1)),
                ('rent_period', models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly')], max_length=1)),
                ('currency', models.CharField(choices=[('U', 'USD'), ('A', 'AMD'), ('R', 'RUB')], max_length=1)),
                ('price', models.PositiveBigIntegerField()),
                ('home_type', models.CharField(choices=[('A', 'Apartment'), ('H', 'House'), ('T', 'Townhome')], max_length=1)),
                ('year_built', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2021)])),
                ('area', models.PositiveSmallIntegerField()),
                ('lot_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('number_of_floors', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('number_of_rooms', models.PositiveSmallIntegerField()),
                ('furnishing', models.CharField(choices=[('F', 'Full'), ('O', 'Only Kitchen'), ('N', 'None')], max_length=1)),
                ('street_building', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('1', 'Ajapnyak'), ('2', 'Arabkir'), ('3', 'Avan'), ('4', 'Davtashen'), ('5', 'Erebuni'), ('6', 'Kanaker-Zeytun'), ('7', 'Kentron'), ('8', 'Malatia-Sebastia'), ('9', 'Nork-Marash'), ('10', 'Nor Nork'), ('11', 'Nubarashen'), ('12', 'Shengavit')], max_length=2)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('central_heating', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('pwd_accessable', models.BooleanField(default=False)),
                ('elivator', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.listing')),
            ],
        ),
    ]
