# Generated by Django 3.1.1 on 2021-01-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('M', 'Monthly')], max_length=1, null=True),
        ),
    ]
