# Generated by Django 3.1.1 on 2021-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210130_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('AMD', 'AMD'), ('RUB', 'RUB')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('Ajapnyak', 'Ajapnyak'), ('Arabkir', 'Arabkir'), ('Avan', 'Avan'), ('Davtashen', 'Davtashen'), ('Erebuni', 'Erebuni'), ('Kanaker-Zeytun', 'Kanaker-Zeytun'), ('Kentron', 'Kentron'), ('Malatia-Sebastia', 'Malatia-Sebastia'), ('Nork-Marash', 'Nork-Marash'), ('Nor Nork', 'Nor Nork'), ('Nubarashen', 'Nubarashen'), ('Shengavit', 'Shengavit')], max_length=16),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furnishing',
            field=models.CharField(choices=[('Full', 'Full'), ('Only Kitchen', 'Only Kitchen'), ('None', 'None')], max_length=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Townhome', 'Townhome')], max_length=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transaction',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=4),
        ),
    ]
