# Generated by Django 3.1.1 on 2021-02-02 09:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210131_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[100, 70], upload_to='images/%Y/%m/%d'),
        ),
    ]
