# Generated by Django 3.1.1 on 2021-02-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210202_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
