# Generated by Django 3.1.1 on 2021-02-08 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210208_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
