# Generated by Django 3.1.1 on 2021-03-11 18:03

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210305_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_medium',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
