# Generated by Django 3.1.1 on 2021-03-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210311_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image_medium',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
