# Generated by Django 3.1.1 on 2021-03-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210311_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='image',
            new_name='image_medium',
        ),
    ]
