# Generated by Django 3.1.1 on 2021-03-13 20:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210313_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image_medium',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
