# Generated by Django 3.1.1 on 2021-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210314_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image_medium',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
